### ISSUE TITLE
Accessibility: screen readers having problems reading dialog components after using keyboard trap

### ISSUE THREAD

**Issue by sendlo** [ianmcburnie/jquery-keyboard-trap#1]
After using the keyboard trap on a dialog the accessibility features on iOS (at least) were having problems reading the components within the dialog.

Ian, to reproduce see the following internal eBay Jira issues:

MTRSBUY-6036
MTRSBUY-6037	
MTRSBUY-6038

**Comment by ianmcburnie** [comment]
Turns out this was a problem with the screenreader trap instead. That issue was fixed:

https://github.com/ianmcburnie/jquery-screenreader-trap/commit/46eda5d2fef00cd6a4a214abba20cc784a6b9bce

Closing ticket.
